#!/bin/bash
# A Simple Shell Script To Get Linux Network Information
# Adapted from Vivek Gite - 30/Aug/2009 by LVH - 2017

#value=$(< template2019)

for file in People/*.pdf;  

do

year=$(date +%Y)
file=${file##*/}
echo ${file}
nameyear=${file%.*} 
echo ${year}
name=${nameyear/${year}/} 
echo ${name}
while read -r first_name mail; do
	# echo ${first_name}
	# echo ${name}
	if [ "${name}" == "${first_name}" ]  
	then
		mail_to_send=${mail} 
echo ${mail_to_send}
sendemail -f cacahuete.xmas.vh@gmail.com -t ${mail_to_send} -u "[${year} VH CACAHUETE] Official Selection" -a People/${nameyear}.pdf -s smtp.gmail.com:587 -o tls=yes -xu cacahuete.xmas.vh@gmail.com -xp HardPassword -o message-file="template${year}.html" -o message-content-type=html -o message-charset=utf-8
	fi
done < "data/mail"


done;


